version: "2"
exclude_patterns:
  - "src/database/"
  - "src/models/"
  - "src/middlewares/"
  - "src/controllers/tripController.js"
  - "src/services/requestService.js"
  - "**/test/"
  - "./src/utils/emailTemplates/confirmAccountTemplate.js"
  - "./src/utils/emailTemplates/passwordRecoveryTemplate.js"
  - "./src/utils/emailTemplates/tripRequestTemplate.js"
  - "./src/utils/emailTemplates/tripFeedbackTemplate.js"
  - "./src/utils/emailTemplatesFunction.js"